### ISSUE TITLE
Feather Falling gives you additional hp.

### ISSUE THREAD

**Issue by RuZZnGG** [AmyMialeeMods/no-enchant-cap#32]
When you wear boots with Feather Falling (even don't need to be higher than level 4), instead of loosing less hp, you not only take no damage, you receive an "absorption" effect additional hearts.

**Comment by buttermyeggrolll** [comment]
This happens when having 4 pieces of protection 4 and Feather-Falling 4, it doesnt happen when only having boots with Protection 4 and Feather-Falling 4. Though it also happens if you have any pieces of armor with non-vanilla level of protection (Protection 5 and above). I would love it if this got fixed because it kind-of ruins the game. Having mixed protection enchants doesn't give extra hearts, only when feather falling gets added or when the protection level goes above 4.

**Comment by SCGCrew** [comment]
Using the End fountain also works to clear the additional hearts.

**Comment by RupeeMiner** [comment]
In an attempt to avoid the feather falling issue, I reverted to the previous forge version of the mod, and it "too expensive" still shows up no matter what I do. Renaming the item appears to make it go away, but when clicked on, it takes your levels until you get more experience and reverts to showing the "too expensive" text

**Comment by AmyMialee** [comment]
> In an attempt to avoid the feather falling issue, I reverted to the previous forge version of the mod, and it "too expensive" still shows up no matter what I do. Renaming the item appears to make it go away, but when clicked on, it takes your levels until you get more experience and reverts to showing the "too expensive" text

if you're using the mod client side it's impossible for too expensive to appear

**Comment by AmyMialee** [comment]
> When you wear boots with Feather Falling (even don't need to be higher than level 4), instead of loosing less hp, you not only take no damage, you receive an "absorption" effect additional hearts.

is this on forge or fabric and does it happen on the other one

**Comment by RuZnRU** [comment]
> > When you wear boots with Feather Falling (even don't need to be higher than level 4), instead of loosing less hp, you not only take no damage, you receive an "absorption" effect additional hearts.
> 
> is this on forge or fabric and does it happen on the other one

Fabric, i don't know if Forge version have the issue.

**Comment by CaramelTurbine** [comment]
Im having this issue as well. Even if its a vanilla issue, and cant be fixed, could you add configs for new enchant caps, or allow admins to specify which enchantments can be stacked?

**Comment by VibronicSine** [comment]
It also happens with full Projectile Protection IV set and getting shot by an arrow (from dispenser or skeleton or other source). I think it's related to how you've implemented the workaround for the 80% damage reduction cap from all the different types of protection enchantments. Because for example a full set of projectile protection IV would get you way past the 80% cap (it's 8% per level so a full set would be 128% theoretically. And I just tested also the higher damage you take the more hearts you get.

**Comment by amer776** [comment]
> 

Hey did you ever find a solution for this problem

**Comment by AmyMialee** [comment]
fixed 2.2.6

**Comment by amer776** [comment]
I know this issue is closed but can you make the same fix but for version 1.19.2,  or make the 2.2.6 1.19.3 release work with 1.19.2
